name: Frontend Sonar Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Sonar Scan
      run: npx sonar-scanner \
        -Dsonar.projectKey=skills-frontend \
        -Dsonar.organization=rathi9641 \ 
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}