name: Deploy React Frontend to Azure

on:
  push:
    branches:
      - main

# ✅ ADD THIS BLOCK (VERY IMPORTANT)
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install
        run: npm install

      - name: Build React App
        run: CI=false npm run build

      # ✅ Azure Login (OIDC)
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0A874D2E9FC94543BC90EF8F4037770B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F6A4593FCB8F4AAFA4BE5689D5D429A0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7D6E65914067497EAB6307423BA85FB1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: skillsfrontend
          package: build
